name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3

      - name: Build test image
        uses: docker/build-push-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          context: .
          load: true
          tags: python-builder-test:latest
          target: test
          build-args: |
            PYTHON_VERSION=3.13.2

      - name: Run tests
        run: |
          chmod +x ./scripts/run_tests.sh
          ./scripts/run_tests.sh

      - name: Test all stages
        run: |
          # Test development stage
          docker build --target development .
          # Test builder stage
          docker build --target builder .
          # Test production stage
          docker build --target production .