name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d0a620d367810f56d901f6bae # v3.0.0

      - name: Build test image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: .
          load: true
          tags: python-builder-test:latest
          target: test
          build-args: |
            PYTHON_VERSION=3.13.2

      - name: Run tests
        run: |
          chmod +x ./scripts/run_tests.sh
          ./scripts/run_tests.sh

      - name: Test all stages
        run: |
          # Test development stage
          docker build --target development .
          # Test builder stage
          docker build --target builder .
          # Test production stage
          docker build --target production .